[build]
buildCommand = "pnpm --filter @picflow/api prisma:generate && pnpm --filter @picflow/api build"

[deploy]
startCommand = "node_modules/.bin/prisma migrate deploy --schema=apps/api/prisma/schema.prisma && node apps/api/dist/main.js"
